INSERT INTO ARMA (DS_ARMA, DS_CAMINHO_IMAGEM, IE_ATIVO) VALUES 
	  ('Caixa de giz', '~/Content/Imagens/CartasArmas/imgCartaCaixaDeGiz.svg', 1)
	, ('Monitor', '~/Content/Imagens/CartasArmas/imgCartaMonitor.svg', 1)
	, ('Teclado', '~/Content/Imagens/CartasArmas/imgCartaTeclado.svg', 1)
	, ('Projetor', '~/Content/Imagens/CartasArmas/imgCartaProjetor.svg', 1) 
	, ('Lista de exercícios', '~/Content/Imagens/CartasArmas/imgCartaListaDeExercicios.svg', 1) 
	, ('Pendrive', '~/Content/Imagens/CartasArmas/imgCartaPendrive.svg', 1)
	, ('Cadeira quebrada', '~/Content/Imagens/CartasArmas/imgCartaCadeiraQuebrada.svg', 1)
	, ('Pomba', '~/Content/Imagens/CartasArmas/imgCartaPomba.svg', 1)

INSERT INTO "LOCAL" (DS_LOCAL, DS_CAMINHO_IMAGEM, NR_LINHA_1, NR_COLUNA_1, NR_LINHA_2, NR_COLUNA_2, IE_ATIVO) VALUES 
	  ('Santhiago', '~/Content/Imagens/CartasLocais/imgCartaSanthiago.svg', 1, 1, 2, 2, 1)
	, ('Centro Acadêmico', '~/Content/Imagens/CartasLocais/imgCartaCentroAcademico.svg', 1, 1, 2, 2, 1)
	, ('Ginásio', '~/Content/Imagens/CartasLocais/imgCartaGinasio.svg', 1, 1, 2, 2, 1)
	, ('Prédio A', '~/Content/Imagens/CartasLocais/imgCartaPredioA.svg', 1, 1, 2, 2, 1)
	, ('Prédio B', '~/Content/Imagens/CartasLocais/imgCartaPredioB.svg', 1, 1, 2, 2, 1)
	, ('Praça', '~/Content/Imagens/CartasLocais/imgCartaPraca.svg', 1, 1, 2, 2, 1)
	, ('Etec', '~/Content/Imagens/CartasLocais/imgCartaEtec.svg', 1, 1, 2, 2, 1)
	, ('Cantina A/B', '~/Content/Imagens/CartasLocais/imgCartaCatinaAB.svg', 1, 1, 2, 2, 1)
	, ('Auditório', '~/Content/Imagens/CartasLocais/imgCartaAuditorio.svg', 1, 1, 2, 2, 1)

INSERT INTO SUSPEITO (ID_LOCAL, DS_SUSPEITO, DS_CAMINHO_IMAGEM, IE_ATIVO) VALUES 
	    (1, 'Reitor', '~/Content/Imagens/CartasSuspeitos/imgCartaReitor.svg', 1)
	  , (1, 'Diretora', '~/Content/Imagens/CartasSuspeitos/imgCartaDiretora.svg', 1)
	  , (1, 'Professora', '~/Content/Imagens/CartasSuspeitos/imgCartaProfessora.svg', 1)
	  , (1, 'Estudante', '~/Content/Imagens/CartasSuspeitos/imgCartaEstudante.svg', 1)
	  , (1, 'Zelador', '~/Content/Imagens/CartasSuspeitos/imgCartaZelador.svg', 1)
	  , (1, 'Policial', '~/Content/Imagens/CartasSuspeitos/imgCartaPolicial.svg', 1)
	  , (1, 'Repóter', '~/Content/Imagens/CartasSuspeitos/imgCartaReporter.svg', 1)
	  , (1, 'Bibliotecária','~/Content/Imagens/CartasSuspeitos/imgCartaBibliotecaria.svg', 1)