CREATE TABLE dbo.SALA
(
  ID_SALA           INT IDENTITY(1000,1) PRIMARY KEY,
  ID_JOGADOR_SALA   INT FOREIGN KEY REFERENCES JOGADOR_SALA(ID_JOGADOR_SALA) NULL,
  DT_CRIACAO        DATETIME NOT NULL,
  IE_ATIVO          BIT DEFAULT 1
)