CREATE TABLE dbo.ARMA_JOGADOR_SALA(
  ID_ARMA_JOGADOR_SALA  INT IDENTITY(1,1) PRIMARY KEY,
  ID_JOGADOR_SALA       INT FOREIGN KEY REFERENCES JOGADOR(ID_JOGADOR) NOT NULL,
  ID_ARMA               INT FOREIGN KEY REFERENCES ARMA(ID_ARMA) NOT NULL,
  IE_ATIVO              BIT DEFAULT 1
)