CREATE TABLE dbo.HISTORICO
(
  ID_HISTORICO  INT IDENTITY(1,1) PRIMARY KEY,
  ID_SALA       INT FOREIGN KEY REFERENCES SALA(ID_SALA) NOT NULL,
  DS_EVENTO     VARCHAR(500) NOT NULL,
  DT_EVENTO     DATETIME NOT NULL,
  IE_ATIVO      BIT DEFAULT 1
)