CREATE TABLE dbo.SUSPEITO 
(
  ID_SUSPEITO               INT IDENTITY(1,1) PRIMARY KEY,
  ID_LOCAL                  INT FOREIGN KEY REFERENCES LOCAL(ID_LOCAL) NULL,
  DS_SUSPEITO               VARCHAR(100) NOT NULL,
  DS_CAMINHO_IMAGEM         VARCHAR(200) NOT NULL,
  DS_CAMINHO_IMAGEM_TOKEN   VARCHAR(200) NOT NULL,
  IE_ATIVO                  BIT DEFAULT 1
)