CREATE TABLE dbo.LOCAL
(
  ID_LOCAL                  INT IDENTITY(1,1) PRIMARY KEY,
  DS_LOCAL                  VARCHAR(100) NOT NULL,
  DS_CAMINHO_IMAGEM         VARCHAR(200) NOT NULL,
  NR_LINHA_1                INT NOT NULL,
  NR_COLUNA_1               INT NOT NULL,
  NR_LINHA_2                INT NOT NULL,
  NR_COLUNA_2               INT NOT NULL,
  ID_LOCAL_PASSAGEM_SECRETA INT FOREIGN KEY REFERENCES LOCAL(ID_LOCAL),
  IE_ATIVO                  BIT DEFAULT 1
)